### PR TITLE
Data documentation

### PR DESCRIPTION
**Pull request by jonathastavares**
This is the first milestone for my Ruby on Rails Social Media Project.

In this milestone, I designed a Data Architecture Diagram for the database, It was saved in a PDF file under the Docs folder.

Designed using: Lucidchart

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad**. 

### Well-done 💯 
    1. The ERD is perfectly set up. 👍🏽  Just one or two things missing

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [ ] All PKs should be represented as ID and not as xxx_id. The latter is only for FKs. Adjust all your PKs to match this standard.

1. One Friendship  is sent by only One User.
2. One User can send many Friendships.
3. One Friendship is received by only One User.
4. One User can receive many Friendships.

You have set up only the second and fourth associations. Add the remaining two associations. 

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Comment by jonathastavares** [comment]
I changed the ID's names, but about the associations, the same line represents all 4 associations you mentioned.

1 - One Friendship is sent by only one User.
2 - One User can send many Friendships.
3 - One Friendship is received by only one User.
4 - One User can receive many Friendships.

Please let me know if you need any changes, but I guess it's correct.

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**Well done lad and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The PKs are now standard. 👍🏽 

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] Adjust your tables (user and friendship) to have this representation. This will make sense entirely only when you get to the third milestone. This basically brings about the two-way association and a second row can be created.

Screenshot from 2021-07-09 02-35-57 Screenshot from 2021-07-09 02-37-17

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by george-shammar — APPROVED** [review]
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: 

Thank you for implementing the required change from the last review.

Your associations are correctly modeled.

I'm happy to approve this milestone.

You may proceed to merge this branch.

I wish you good luck with your future projects.

Cheers. :smile:

**Pull request merged**
